---
title: "EPSY 5261: Slides"
format: 
  html:
    header-includes: |
      <script src="https://kit.fontawesome.com/e5da75ca36.js" crossorigin="anonymous"></script>
---

## Fall 2024 Slides

1. Welcome to 5261
2. [Introduction to Coding](d02-introduction-to-coding.html)
3. [Introduction to R and R Studio](d03-introduction-to-r-and-rstudio.html)
4. Data and Codebooks --- *No Slides*
5. [Variables and Graphs](d05-variables-and-graphs.html)
6. [Describing Distributions](d06-describing-distributions.html)
7. [Estimating Uncertainty](d07-estimating-uncertainty.html)
8. [Introduction to Hypothesis Testing](d08-introduction-to-hypothesis-testing.html)
9. [Simulation-Based Hypothesis Testing](d09-simulation-based-hypothesis-testing.html)
10. [Study Design: Generalizability](d10-study-design-generalizability.html)
11. [Hypothesis Testing with the *t*-Distribution](d11-hypothesis-testing-with-the-t-distribution.html)
12. [Hypothesis Testing for Proportions](d12-hypothesis-testing-for-proportions.html)
13. [Study Design: Causal Claims](d13-study-design-causal-claims.html)
14. [Hypothesis Testing for Comparing Two Means](d14-hypothesis-testing-for-comparing-two-means.html)
15. [Hypothesis Testing for Comparing Two Proportions](d15-hypothesis-testing-for-comparing-two-proportions.html)
16. *No Class: Mental Health Day*
17. [Introduction to Confidence Intervals](d17-introduction-to-confidence-intervals.html)
18. [Confidence Intervals for a Single Mean](d18-confidence-interval-for-a-single-mean.html)
19. [Confidence Intervals for a Single Proportion](d19-confidence-interval-for-a-single-proportion.html)
20. [Confidence Intervals for Comparing Two Groups](d20-confidence-interval-for-comparing-two-groups.html)
21. [Practice Confidence Intervals](d21-practice-confidence-intervals.html)
22. [Exploring Effect Size](d22-exploring-effect-size.html)
23. [Introduction to Correlation](d23-introduction-to-correlation.html)
24. [Introduction to Linear Regression](d24-introduction-to-linear-regression.html)
25. [Hypothesis Test for a Slope](d25-hypothesis-test-for-a-slope.html)
26. *No Class: Thanksgiving Break*
27. [Assumptions for Linear Regression](d27-assumptions-for-linear-regression.html)
28. Linear Regression: Practice  --- *No Slides*
29. TBA / [Review](d29-review.html)

